@startuml

class GameLoop{
+{static}void mapLoop();
+{static} void initGame();
+{static} void newGame();
+{static} void npcLoop(NPC &talkedNPC);
+{static} void commandLoop();
+{static} void gameInterface();
+{static} void battleLoop(Character &character);
+{static} void shopLoop(NPC &npc);
+{static} bool canLoad();
}

@enduml