@startuml

class Mission{
+Mission(int id)
+void showDescription()
+bool checkFinished()
+void missionFinish(Player &player)
+void loadMission(ifstream& f,string owner, string path)
+void saveMission(string owner, string path)
+int id
+string nameEN;
+string nameCN;
+string description;
+bool isAccepted;
+bool isFinished;
+bool isProcess;
+int bonusMoney;
+int bonusExperiencePoint;
+string assigner;
+map<int, int> requiredItem;
}
@enduml